import {
  HiOutlineChartBar,
  HiOutlineMagnifyingGlass,
  HiOutlineShieldCheck,
  HiOutlineLink,
  HiOutlineFilm,
  HiOutlineMicrophone,
  HiOutlineCalendarDays,
  HiOutlineUsers,
  HiOutlineExclamationTriangle,
  HiOutlineCurrencyDollar,
  HiOutlineArrowPath,
  HiOutlineArrowsRightLeft,
  HiOutlinePresentationChartLine,
  HiOutlineMapPin,
  HiOutlineDocumentText,
  HiOutlineCheckCircle,
  HiOutlineXCircle,
  HiOutlineClock,
  HiOutlineBolt,
  HiOutlineEye,
  HiOutlineDocumentCheck,
  HiOutlineGlobeAlt,
  HiOutlineMagnifyingGlassCircle,
  HiOutlineBuildingOffice2,
  HiOutlineChatBubbleLeftRight,
  HiOutlineSignal,
  HiOutlineHandRaised,
  HiOutlineTag,
  HiOutlineLockClosed,
  HiOutlineClipboardDocumentList,
  HiOutlineSpeakerWave,
  HiOutlineMusicalNote,
  HiOutlinePaintBrush,
  HiOutlineSquares2X2,
  HiOutlineFire,
  HiOutlineNewspaper,
  HiOutlineUserGroup,
  HiOutlineUser,
  HiOutlineMegaphone,
  HiOutlineLightBulb,
  HiOutlineFaceSmile,
  HiOutlineArrowTrendingUp,
  HiOutlineStop,
  HiOutlineInformationCircle,
  HiOutlineExclamationCircle,
  HiOutlinePause,
  HiOutlinePlay,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineBriefcase,
  HiOutlineTruck,
  HiOutlineShieldExclamation,
  HiOutlineWrench,
  HiOutlineQuestionMarkCircle,
  HiOutlineHandThumbUp,
  HiOutlineHandThumbDown,
  HiOutlinePhoto,
  HiOutlineMagnifyingGlassPlus,
  HiOutlineArrowUpTray,
  HiOutlineShare,
  HiOutlinePencilSquare,
  HiOutlineStar,
  HiOutlineFunnel,
} from "react-icons/hi2";

export const ICONS = {
  // Navigation / Tabs
  chart: <HiOutlineChartBar size={18} />,
  search: <HiOutlineMagnifyingGlass size={18} />,
  shield: <HiOutlineShieldCheck size={18} />,
  link: <HiOutlineLink size={18} />,
  film: <HiOutlineFilm size={18} />,
  microphone: <HiOutlineMicrophone size={18} />,
  calendar: <HiOutlineCalendarDays size={18} />,
  users: <HiOutlineUsers size={18} />,
  alert: <HiOutlineExclamationTriangle size={18} />,
  dollar: <HiOutlineCurrencyDollar size={18} />,
  refresh: <HiOutlineArrowPath size={18} />,
  compare: <HiOutlineArrowsRightLeft size={18} />,
  presentation: <HiOutlinePresentationChartLine size={18} />,
  mapPin: <HiOutlineMapPin size={18} />,
  document: <HiOutlineDocumentText size={18} />,

  // Status / Actions
  check: <HiOutlineCheckCircle size={18} />,
  cross: <HiOutlineXCircle size={18} />,
  clock: <HiOutlineClock size={18} />,
  bolt: <HiOutlineBolt size={18} />,
  eye: <HiOutlineEye size={18} />,
  documentCheck: <HiOutlineDocumentCheck size={18} />,
  globe: <HiOutlineGlobeAlt size={18} />,
  magnifyCircle: <HiOutlineMagnifyingGlassCircle size={18} />,
  building: <HiOutlineBuildingOffice2 size={18} />,
  chat: <HiOutlineChatBubbleLeftRight size={18} />,
  signal: <HiOutlineSignal size={18} />,
  hand: <HiOutlineHandRaised size={18} />,
  tag: <HiOutlineTag size={18} />,
  lock: <HiOutlineLockClosed size={18} />,
  clipboard: <HiOutlineClipboardDocumentList size={18} />,
  speaker: <HiOutlineSpeakerWave size={18} />,
  music: <HiOutlineMusicalNote size={18} />,
  paint: <HiOutlinePaintBrush size={18} />,
  grid: <HiOutlineSquares2X2 size={18} />,
  fire: <HiOutlineFire size={18} />,
  newspaper: <HiOutlineNewspaper size={18} />,
  userGroup: <HiOutlineUserGroup size={18} />,
  user: <HiOutlineUser size={18} />,
  megaphone: <HiOutlineMegaphone size={18} />,
  lightBulb: <HiOutlineLightBulb size={18} />,
  smile: <HiOutlineFaceSmile size={18} />,
  trending: <HiOutlineArrowTrendingUp size={18} />,
  stop: <HiOutlineStop size={18} />,
  info: <HiOutlineInformationCircle size={18} />,
  exclamation: <HiOutlineExclamationCircle size={18} />,
  pause: <HiOutlinePause size={18} />,
  play: <HiOutlinePlay size={18} />,
  settings: <HiOutlineAdjustmentsHorizontal size={18} />,
  briefcase: <HiOutlineBriefcase size={18} />,
  truck: <HiOutlineTruck size={18} />,
  shieldAlert: <HiOutlineShieldExclamation size={18} />,
  wrench: <HiOutlineWrench size={18} />,
  question: <HiOutlineQuestionMarkCircle size={18} />,
  thumbUp: <HiOutlineHandThumbUp size={18} />,
  thumbDown: <HiOutlineHandThumbDown size={18} />,
  photo: <HiOutlinePhoto size={18} />,
  magnifyPlus: <HiOutlineMagnifyingGlassPlus size={18} />,
  upload: <HiOutlineArrowUpTray size={18} />,
  share: <HiOutlineShare size={18} />,
  pencil: <HiOutlinePencilSquare size={18} />,
  star: <HiOutlineStar size={18} />,
  filter: <HiOutlineFunnel size={18} />,
} as const;

// Agent type icons
export const AGENT_ICONS: Record<string, React.ReactNode> = {
  director: <HiOutlineFilm size={18} />,
  research: <HiOutlineMagnifyingGlass size={18} />,
  legal: <HiOutlineShieldCheck size={18} />,
  continuity: <HiOutlineLink size={18} />,
  storyboard: <HiOutlinePhoto size={18} />,
  tts: <HiOutlineMicrophone size={18} />,
  schedule: <HiOutlineCalendarDays size={18} />,
  stakeholder: <HiOutlineBuildingOffice2 size={18} />,
  "risk-dashboard": <HiOutlineExclamationTriangle size={18} />,
};

// Severity icons
export const SEVERITY_ICONS: Record<string, React.ReactNode> = {
  critical: <HiOutlineExclamationCircle size={16} className="text-red-500" />,
  high: <HiOutlineExclamationTriangle size={16} className="text-orange-500" />,
  medium: <HiOutlineInformationCircle size={16} className="text-yellow-500" />,
  low: <HiOutlineCheckCircle size={16} className="text-green-500" />,
};

// Genre icons
export const GENRE_ICONS: Record<string, string> = {
  "Action/Thriller": "Action",
  "Period Drama": "Period",
  "Science Fiction": "Sci-Fi",
};

export default ICONS;
